app/src/Doctrine/Entity/User/UserPrize.php
<?php
/**
 * Created by PhpStorm.
 * User: dump
 * Date: 10/01/19
 * Time: 22:08
 */

namespace App\Doctrine\Entity\User;

use App\Doctrine\Entity\User;
use App\Prize\PrizeType;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Doctrine\Repository\User\UserPrizeRepository")
 */
class UserPrize
{
    public const STATUS_NEW = 0;
    public const STATUS_CLAIMED = 1;
    public const STATUS_CANCELED = 2;

    /**
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned": true})
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="App\Doctrine\Entity\User", inversedBy="prizes")
     */
    private $user;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime|null
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $claimedAt;

    /**
     * @var int
     * @ORM\Column(type="smallint", options={"default"=0})
     */
    private $status = 0;

    /**
     * @var int
     * @ORM\Column(type="smallint")
     */
    private $type;

    /**
     * @var array
     * @ORM\Column(type="json_array")
     */
    private $options;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser(User $user): void
    {
        $this->user = $user;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @return \DateTime|null
     */
    public function getClaimedAt(): ?\DateTime
    {
        return $this->claimedAt;
    }

    /**
     * @param \DateTime $claimedAt
     */
    public function setClaimedAt(\DateTime $claimedAt): void
    {
        $this->claimedAt = $claimedAt;
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    public function getHumanStatus(): string {
        $types = [
            self::STATUS_NEW => 'New',
            self::STATUS_CLAIMED => 'Claimed',
            self::STATUS_CANCELED => 'Refused'
        ];

        return $types[$this->getType()] ?? '';
    }

    /**
     * @param int $status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * @return int
     */
    public function getType(): int
    {
        return $this->type;
    }

    public function getHumanType(): string {
        $types = [
            PrizeType::MONEY => 'Money',
            PrizeType::BONUS => 'Bonus',
            PrizeType::ITEM => 'Item'
        ];

        return $types[$this->getType()] ?? '';
    }

    /**
     * @param int $type
     */
    public function setType(int $type): void
    {
        $this->type = $type;
    }

    /**
     * @return array
     */
    public function getOptions(): array
    {
        return $this->options;
    }

    /**
     * @param array $options
     */
    public function setOptions(array $options): void
    {
        $this->options = $options;
    }
}

app/src/Controller/Site/IndexController.php
<?php

namespace App\Controller\Site;

use App\Controller\BaseController;
use App\Doctrine\Entity\User\UserPrize;
use App\Doctrine\Repository\User\UserPrizeRepository;
use App\Prize\PrizeManager;
use App\Prize\Type\MoneyPrize;
use App\Prize\Type\PrizeTypeInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Template
 * @Route("/")
 */
class IndexController extends BaseController {

    /**
     * @var UserPrizeRepository
     */
    protected $repository;

    /**
     * IndexController constructor.
     * @param UserPrizeRepository $repository
     */
    public function __construct(UserPrizeRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route(name="site-index")
     * @param Request $request
     * @return array
     */
    public function index(Request $request, PaginatorInterface $paginator)
    {
        return array(
            'pagination' => $paginator->paginate(
                $this->repository->getUserList($this->getUser()),
                $request->query->get('page', 1),
                $this->paginationLimit
            )
        );
    }

    /**
     * @Route("/get-prize", name="site-index:get-prize")
     * @param PrizeManager $prizeManager
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function getPrize(PrizeManager $prizeManager) {
        /** @var PrizeTypeInterface $prize */
        $prize = $prizeManager->getRandomPrize();

        $userPrize = new UserPrize();
        $userPrize->setType($prize->getType());
        $userPrize->setUser($this->getUser());
        $userPrize->setOptions($prize->store());

        $this->repository->save($userPrize);

        return $this->redirect($this->generateUrl('site-index'));
    }

    /**
     * @Route("/refuse/{id}", requirements={"id" = "\d+"}, name="site-index:refuse", methods={"post"})
     * @ParamConverter("userPrize")
     * @param Request $request
     * @param UserPrize $userPrize
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function refuse(Request $request, UserPrize $userPrize)
    {
        if ($this->isCsrfTokenValid('prize_refuse', $request->get('token'))) {
            $this->repository->refuse($userPrize);
        }

        return $this->back($request->headers->get('referer'), $this->generateUrl('site-index'));
    }

    /**
     * @Route("/claim-as-bonus/{id}", requirements={"id" = "\d+"}, name="site-index:claim-as-bonus", methods={"post"})
     * @ParamConverter("userPrize")
     * @param Request $request
     * @param UserPrize $userPrize
     * @param PrizeManager $prizeManager
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function claimAsBonus(Request $request, UserPrize $userPrize, PrizeManager $prizeManager)
    {
        if ($this->isCsrfTokenValid('prize_refuse', $request->get('token'))) {

            /** @var MoneyPrize $prize */
            $prize = $prizeManager->restorePrize($userPrize->getType(), $userPrize->getOptions());

            if($prize instanceof MoneyPrize) {
                $prize->setClaimAsBonus(true);
                $userPrize->setOptions($prize->store());

                $this->repository->update($userPrize);
            } else {
                //error
            }


        }

        return $this->back($request->headers->get('referer'), $this->generateUrl('site-index'));
    }
}

app/templates/site/index/index.html.twig
{% extends 'site/layout.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <h2 class="sub-header">{{ "site.prize.title"|trans }}</h2>
        </div>
        <div class="col-lg-12 gridWithMarginTopBottom">
            <a class="btn btn-success" href="{{ path('site-index:get-prize') }}">{{ "site.prize.create"|trans }}</a>
        </div>
        <div class="col-lg-12">
            {% if pagination.getTotalItemCount == 0 %}
                <div class="alert alert-warning">
                    {{ "site.prize.empty"|trans }}
                </div>
            {% else %}
                <table class="table table-striped table-condensed">
                    <tr>
                        <th width="40">ID</th>
                        <th>{{ "site.prize.createdAt"|trans }}</th>
                        <th>{{ "site.prize.claimedAt"|trans }}</th>
                        <th>{{ "site.prize.status"|trans }}</th>
                        <th>{{ "site.prize.type"|trans }}</th>
                        <th></th>
                    </tr>
                    {% for prize in pagination %}
                        <tr>
                            <td>{{ prize.id }}</td>
                            <td>{{ prize.createdAt|date("d.m.Y H:i:s") }}</td>
                            <td>{{ prize.claimedAt ? prize.claimedAt|date("d.m.Y H:i:s") : ''}}</td>
                            <td>{{ prize.humanStatus }}</td>
                            <td>{{ prize.humanType }}</td>
                            <td>
                                {% if prize.type == constant("App\\Prize\\PrizeType::MONEY") %}
                                    <button class="btn btn-warning btn-xs"
                                            data-toggle="modal" data-target="#deleteModal"
                                            data-replace-action="{{ path('site-index:claim-as-bonus', {id: prize.id}) }}"
                                            data-replace-body="{{ "site.prize.asBonus"|trans({"%name%" : prize.id})|escape }}"
                                    >{{ "site.button.asBonus" | trans }}</button>
                                {% endif %}

                                <button class="btn btn-danger btn-xs"
                                        data-toggle="modal" data-target="#deleteModal"
                                        data-replace-action="{{ path('site-index:refuse', {id: prize.id}) }}"
                                        data-replace-body="{{ "site.prize.refuse"|trans({"%name%" : prize.id})|escape }}"
                                >{{ "site.button.refuse" | trans }}</button>
                            </td>
                        </tr>
                    {% endfor %}
                </table>

                {% include 'admin/layout_block/delete_modal.html.twig' with {'csrf': csrf_token('prize_refuse')} %}
                {{ knp_pagination_render(pagination) }}
            {% endif %}
        </div>
    </div>
{% endblock body %}